### ISSUE TITLE
No working in X86 linux kernel

### ISSUE THREAD

**Issue by roothaxor** [cryptolok/MorphAES#1]
error: 'movabs' is only supported in 64-bit mode"?
help bruh i am using intel shit cant run 64-bit mode
also getting Error:  bad register name ' this type many times with diff registers

**Comment by cryptolok** [comment]
Can I see your /proc/cpuinfo ?
Also, are you virtualizing 32-bit machine on a 64-bit one?

**Comment by roothaxor** [comment]
yes sir using virtualization have x86 kali linux installed

**Comment by cryptolok** [comment]
OK, so can you paste the result of `cat /proc/cpuinfo`, please?

**Comment by roothaxor** [comment]
processor   : 0
vendor_id   : GenuineIntel
cpu family  : 6
model       : 42
model name  : Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz
stepping    : 7
microcode   : 0x25
cpu MHz     : 2294.849
cache size  : 3072 KB
physical id : 0
siblings    : 4
core id     : 0
cpu cores   : 4
apicid      : 0
initial apicid  : 0
fdiv_bug    : no
f00f_bug    : no
coma_bug    : no
fpu     : yes
fpu_exception   : yes
cpuid level : 13
wp      : yes
flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss ht nx rdtscp lm constant_tsc arch_perfmon pebs bts xtopology tsc_reliable nonstop_tsc aperfmperf pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm arat epb pln pts dtherm tsc_adjust
bugs        :
bogomips    : 4589.69
clflush size    : 64
cache_alignment : 64
address sizes   : 42 bits physical, 48 bits virtual

**Comment by cryptolok** [comment]
Well, it's totally normal.
You see, in order to work, your machine (physical or virtual) has to have [AES-NI](http://ark.intel.com/search/advanced/?s=t&AESTech=true) support.
Regardless the fact that, it is exactly your case, my code uses 64-bit registers, with the appropriate instructions.
Thus, it is physically impossible to execute the code on your machine.
Newertheless, I think it's possible to port my code for 32-bit, but it will be really hard :) basically I have to rewrite the whole logic and math from zero, which is a pretty good exercise, but since 32-bit AES-NI is very uncommon, I don't see any significant reason to do it, for now.
If you're willing to do it on your own, then you can fork my code and I wish you a good luck :)
I will change the README although.
Anyway, thanks for your contribution :)

**Comment by roothaxor** [comment]
sure sir when i get time i'll make it nice talk thankyou for your codes
